from .eic_relationship_entity import EicRelationshipEntity
from .published_work_entity import PublishedWorkEntity
from .researcher_entity import ResearcherEntity
from .scientific_serial_publisher_entity import ScientificSerialPublisherEntity
from .student_entity import StudentEntity
from .year_ssp_qualis_relationship_entity import YearSspQualisRelationshipEntity
